/**
 * PERSONAL QR CARD THEMES
 * ─────────────────────────────────────────────────────────────
 * To add a new theme in the future:
 *   1. Add an entry to this array.
 *   2. PublicCard.jsx reads from this to apply styles.
 *   Nothing outside the personal_qr folder changes.
 * ─────────────────────────────────────────────────────────────
 */

export const PERSONAL_QR_THEMES = [
  {
    id: 'minimal',
    name: 'Minimal White',
    emoji: '🤍',
    description: 'Clean white with indigo accents',
    layout: 'minimal',
    preview: {
      headerBg: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
      pageBg: '#f8fafc',
      cardBg: '#ffffff',
      textColor: '#1e293b',
      accentColor: '#4f46e5',
      btnBg: '#4f46e5',
      btnText: '#ffffff',
    },
  },
  {
    id: 'dark',
    name: 'Dark Mode',
    emoji: '🌑',
    description: 'Deep dark with purple glow',
    layout: 'glass',
    preview: {
      headerBg: 'linear-gradient(135deg, #1e1b4b, #312e81)',
      pageBg: '#0f0f0f',
      cardBg: 'rgba(26, 26, 46, 0.4)',
      textColor: '#e2e8f0',
      accentColor: '#818cf8',
      btnBg: '#6d28d9',
      btnText: '#ffffff',
    },
  },
  {
    id: 'neon',
    name: 'Neon Glow',
    emoji: '💜',
    description: 'Dark with hot-pink neon borders',
    layout: 'glass',
    preview: {
      headerBg: 'linear-gradient(135deg, #0f0f0f, #1a0a2e)',
      pageBg: '#0f0f0f',
      cardBg: 'rgba(255,0,128,0.05)',
      textColor: '#ffffff',
      accentColor: '#ff0080',
      btnBg: 'transparent',
      btnText: '#ff0080',
    },
  },
  {
    id: 'corporate',
    name: 'Corporate Blue',
    emoji: '💼',
    description: 'Professional navy for business profiles',
    layout: 'classic',
    preview: {
      headerBg: 'linear-gradient(135deg, #1e3a8a, #2563eb)',
      pageBg: '#f0f4f8',
      cardBg: '#ffffff',
      textColor: '#1e3a8a',
      accentColor: '#2563eb',
      btnBg: '#1e3a8a',
      btnText: '#ffffff',
    },
  },
  {
    id: 'vibrant',
    name: 'Vibrant Gradient',
    emoji: '🌈',
    description: 'Eye-catching rainbow gradient header',
    layout: 'cover',
    preview: {
      headerBg: 'linear-gradient(135deg, #f97316, #ec4899, #8b5cf6)',
      pageBg: '#ffffff',
      cardBg: '#f9fafb',
      textColor: '#111827',
      accentColor: '#ec4899',
      btnBg: 'linear-gradient(135deg, #f97316, #ec4899)',
      btnText: '#ffffff',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Warm',
    emoji: '🌅',
    description: 'Warm orange-red gradient energy',
    layout: 'classic',
    preview: {
      headerBg: 'linear-gradient(135deg, #f97316, #dc2626)',
      pageBg: '#fff7ed',
      cardBg: '#ffffff',
      textColor: '#7c2d12',
      accentColor: '#f97316',
      btnBg: '#f97316',
      btnText: '#ffffff',
    },
  },
  {
    id: 'forest',
    name: 'Forest Green',
    emoji: '🌲',
    description: 'Nature-inspired deep greens',
    layout: 'left',
    preview: {
      headerBg: 'linear-gradient(135deg, #14532d, #15803d)',
      pageBg: '#f0fdf4',
      cardBg: '#ffffff',
      textColor: '#14532d',
      accentColor: '#15803d',
      btnBg: '#15803d',
      btnText: '#ffffff',
    },
  },
  {
    id: 'ocean',
    name: 'Deep Ocean',
    emoji: '🌊',
    description: 'Calm deep-blue teal ocean vibes',
    layout: 'cover',
    preview: {
      headerBg: 'linear-gradient(135deg, #0c4a6e, #0891b2)',
      pageBg: '#ecfeff',
      cardBg: '#ffffff',
      textColor: '#0c4a6e',
      accentColor: '#0891b2',
      btnBg: '#0891b2',
      btnText: '#ffffff',
    },
  },
  {
    id: 'luxury',
    name: 'Black & Gold',
    emoji: '🥇',
    description: 'Premium black with gold accents',
    layout: 'center',
    preview: {
      headerBg: 'linear-gradient(135deg, #000000, #111111)',
      pageBg: '#0a0a0a',
      cardBg: '#1a1a1a',
      textColor: '#fbbf24',
      accentColor: '#fbbf24',
      btnBg: '#fbbf24',
      btnText: '#000000',
    },
  },
  {
    id: 'pastel',
    name: 'Soft Pastel',
    emoji: '🌸',
    description: 'Gentle pink-lavender pastel tones',
    layout: 'glass',
    preview: {
      headerBg: 'linear-gradient(135deg, #e879f9, #a78bfa)',
      pageBg: '#fdf4ff',
      cardBg: 'rgba(255, 255, 255, 0.4)',
      textColor: '#581c87',
      accentColor: '#a855f7',
      btnBg: '#a855f7',
      btnText: '#ffffff',
    },
  },
  {
    id: 'navratri_nights',
    name: 'Navratri Nights',
    emoji: '🥁',
    description: 'Deep festive night with glowing Garba colors',
    layout: 'glass',
    preview: {
      headerBg: 'linear-gradient(135deg, rgba(225,29,72,0.8), rgba(217,119,6,0.8), rgba(22,163,74,0.8))',
      pageBg: 'linear-gradient(rgba(17, 10, 31, 0.7), rgba(17, 10, 31, 0.7)), url("/navratri_bg.jpg") center/cover fixed',
      cardBg: 'rgba(30, 20, 50, 0.6)',
      textColor: '#fef3c7',
      accentColor: '#fbbf24',
      btnBg: '#e11d48',
      btnText: '#ffffff',
    },
  },
  {
    id: 'navratri_festive',
    name: 'Navratri Festive',
    emoji: '🪔',
    description: 'Bright and traditional Indian festive colors',
    layout: 'glass',
    preview: {
      headerBg: 'linear-gradient(135deg, rgba(194,65,12,0.6), rgba(185,28,28,0.6))',
      pageBg: 'linear-gradient(rgba(255, 251, 235, 0.4), rgba(255, 251, 235, 0.4)), url("/navratri_bg.jpg") center/cover fixed',
      cardBg: 'rgba(255, 255, 255, 0.45)',
      textColor: '#7c2d12',
      accentColor: '#c2410c',
      btnBg: '#c2410c',
      btnText: '#ffffff',
    },
  },
];
